"""The storefront: real URLs, server-rendered, with a cart.

Separate from `/v1` on purpose. The JSON API is what a customer's engineers
integrate against; this is what their finance director browses. Sharing a router
would mean the pages inherit bearer-token auth and the API inherits session
cookies, and both would be wrong.

### Why server-rendered

A storefront needs shareable links, a working back button, and a page that means
something before JavaScript runs. A cart with four line items does not justify a
client-side router. The only JavaScript that matters here is the job poller on
`/configure`, and that is genuinely asynchronous work rather than a rendering
strategy.

### Identity

A visitor gets a guest account on first write. That is a real `accounts` row
with a real API key, created lazily, so an order always has an owner and the
same person can later be sent a magic link back into their own work. Nothing
asks them to register before they can see a price.

### The latency problem, and the shape it forces

Fitting a century at a new coordinate is 80-140 seconds. That cannot happen
inside a request, so `POST /configure/{slug}/venue` starts a job and returns
`{"job_id", "status_url"}` immediately; the page polls. Anyone who does not want
to sit and watch can leave an email address and be sent a link back to the
finished quote.
"""

from __future__ import annotations

import json
import logging
import secrets
import time
from pathlib import Path
from typing import Any, Protocol

from fastapi import APIRouter, Form, HTTPException, Request
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse
from fastapi.templating import Jinja2Templates

from . import catalog, checkout, security, service, stations, store

log = logging.getLogger(__name__)

router = APIRouter(include_in_schema=False)

WEB = Path(__file__).resolve().parents[1] / "web"
TEMPLATES = Jinja2Templates(directory=str(WEB / "templates"))
def datefmt(epoch: float | None, fmt: str = "%d %b %Y") -> str:
    return time.strftime(fmt, time.localtime(epoch)) if epoch else "—"


TEMPLATES.env.filters["datefmt"] = datefmt
TEMPLATES.env.globals.update(
    money=catalog.money,
    PRODUCTS=catalog.PRODUCTS,
    DISCLAIMER=(
        "Quotes generated by this engine are indicative estimates for risk "
        "management evaluation. Binding coverage is subject to underwriting "
        "review and issued exclusively through licensed MGA and carrier partners."
    ),
    INVOICE_HEADER="Indicative Parametric Risk Estimate — Not a Binding Policy Contract",
)


# ----------------------------------------------------------------------
# Session identity
# ----------------------------------------------------------------------


def guest_account(request: Request, email: str | None = None, name: str | None = None) -> dict:
    """The account this browser is acting as, created on demand.

    Deliberately lazy: a visitor reading the pricing page should not have a
    database row. The first thing that needs an owner --- a venue, an order ---
    creates one.
    """
    account_id = request.session.get("account_id")
    if account_id:
        with store.connect() as conn:
            row = conn.execute("SELECT * FROM accounts WHERE id = ?", (account_id,)).fetchone()
        if row:
            account = dict(row)
            if email and account["email"].startswith("guest+"):
                # Upgrading a guest to a named account, if the address is free.
                if store.account_by_email(email) is None:
                    with store.connect() as conn:
                        conn.execute(
                            "UPDATE accounts SET email = ?, name = ? WHERE id = ?",
                            (email.lower().strip(), name or account["name"], account_id),
                        )
                    account = store.account_by_key(account["api_key"]) or account
            return account

    if email:
        existing = store.account_by_email(email)
        if existing:
            request.session["account_id"] = existing["id"]
            return existing

    account = store.create_account(
        name or "Guest",
        email or f"guest+{secrets.token_hex(6)}@downside.local",
    )
    request.session["account_id"] = account["id"]
    return account


def adopt_resume_token(request: Request, token: str | None, site_id: str | None) -> bool:
    """Log this browser in as the token's owner. Returns whether it did.

    This is the whole magic-link mechanism, and it is deliberately three lines:
    a valid token writes `account_id` into the session and then **every existing
    ownership check applies unchanged**. Nothing downstream learns about tokens,
    and no authorisation path is duplicated or relaxed to accommodate them.
    """
    payload = security.read_resume_token(token, site_id=site_id)
    if payload is None:
        return False
    request.session["account_id"] = payload["account_id"]
    return True


def current_account(request: Request) -> dict | None:
    account_id = request.session.get("account_id")
    if not account_id:
        return None
    with store.connect() as conn:
        row = conn.execute("SELECT * FROM accounts WHERE id = ?", (account_id,)).fetchone()
    return dict(row) if row else None


def base_context(request: Request, **extra: Any) -> dict:
    cart = checkout.read_cart(request.session)
    return {
        "request": request,
        "cart": cart,
        "cart_count": cart.count,
        "account": current_account(request),
        "products": catalog.PRODUCTS,
        "year": time.localtime().tm_year,
        **extra,
    }


def render(request: Request, template: str, **ctx: Any) -> HTMLResponse:
    # Starlette's request-first signature. The older `(name, context)` form was
    # removed, and its failure mode is an unhelpful `unhashable type: dict`.
    return TEMPLATES.TemplateResponse(request, template, base_context(request, **ctx))


# ----------------------------------------------------------------------
# Marketing pages
# ----------------------------------------------------------------------


@router.get("/", response_class=HTMLResponse)
def home(request: Request) -> HTMLResponse:
    examples = store.list_example_sites()
    hero_site = next(
        (s for s in examples if s.get("station_id") and s.get("station_km") is not None),
        examples[0] if examples else None,
    )
    return render(
        request, "home.html",
        examples=examples[:4],
        hero_site=hero_site,
        weather="clear",
    )


@router.get("/services", response_class=HTMLResponse)
def services(request: Request) -> HTMLResponse:
    return render(request, "services.html", weather="cloud")


@router.get("/services/{slug}", response_class=HTMLResponse)
def service_detail(request: Request, slug: str) -> HTMLResponse:
    product = catalog.get(slug)
    if product is None:
        raise HTTPException(404, "No such service.")
    return render(
        request, "service.html",
        product=product,
        others=[p for p in catalog.PRODUCTS if p.slug != slug],
        weather=_weather_for(slug),
    )


def _weather_for(slug: str) -> str:
    """The canvas state each page opens in. The product, rendered."""
    return {
        "exposure-report": "clear",
        "season-monitor": "snow",
        "parametric-cover": "rain",
        "portfolio-analytics": "cloud",
    }.get(slug, "clear")


# ----------------------------------------------------------------------
# Configure
# ----------------------------------------------------------------------


@router.get("/configure/{slug}", response_class=HTMLResponse)
def configure(
    request: Request,
    slug: str,
    site: str | None = None,
    job_id: str | None = None,
    t: str | None = None,
):
    product = catalog.get(slug)
    if product is None:
        raise HTTPException(404, "No such service.")

    # Before reading the account, so a visitor arriving from a resume link on a
    # device with no cookie is already the owner by the time ownership is checked.
    adopt_resume_token(request, t, site)

    examples = store.list_example_sites()
    account = current_account(request)
    own = store.list_sites(account["id"]) if account else []
    own = [s for s in own if not s.get("is_example")]

    selected = None
    if site:
        selected = store.get_site(site)
        # Example venues are public; anything else must belong to this session.
        if selected and not selected.get("is_example"):
            if not account or selected["account_id"] != account["id"]:
                selected = None

    quote = None
    if selected and selected["status"] == "ready" and product.requires_fit:
        quote = _indicative(selected)

    return render(
        request, "configure.html",
        product=product,
        examples=examples,
        own_sites=own,
        selected=selected,
        station=_station_view(selected) if selected else None,
        quote=quote,
        resume_job=job_id,
        verticals=VERTICALS,
        resume_link=(
            absolute(request, magic_link(selected, slug))
            if selected and selected.get("resume_token") and not selected.get("is_example")
            else None
        ),
        mail_configured=SENDER.configured,
        weather=_weather_for(slug),
    )


VERTICALS = [
    "Ski resort", "Golf resort", "Festival grounds", "Winery & events",
    "Campground group", "Waterfront venue", "Outdoor attraction",
]


def _station_view(site: dict) -> dict | None:
    """What settles this venue's contracts, shaped for display.

    Returns the reanalysis fallback rather than `None` when no station
    qualified, because "we could not find a gauge and are using a model grid
    cell" is information the customer is entitled to before they buy.
    """
    if not site.get("station_id"):
        return {
            "matched": False,
            "note": (
                "No long-record station qualified within "
                f"{stations.DEFAULT_MAX_KM:.0f} km of these coordinates. This venue "
                "falls back to ERA5 reanalysis at its exact position — gap-free and "
                "physically consistent, but a model grid cell rather than a gauge, "
                "with its own basis risk."
            ),
        }

    delta = site.get("station_elevation_delta_m")
    match = stations.StationMatch(
        station_id=site["station_id"],
        name=site.get("station_name") or "",
        lat=float(site["lat"]),
        lon=float(site["lon"]),
        elevation_m=float(site.get("station_elevation_m") or 0.0),
        distance_km=float(site.get("station_km") or 0.0),
        first_year=int(site.get("station_first_year") or 0),
        last_year=int(site.get("station_last_year") or 0),
        elements=(),
        score=0.0,
        elevation_delta_m=float(delta) if delta is not None else None,
        elevation_warning=bool(site.get("station_elevation_warning") or 0),
    )
    return {
        "matched": True,
        "id": match.station_id,
        "name": match.name.title(),
        # Rounded here rather than in the template: this view feeds both Jinja
        # and the JSON the configure page renders client-side, and 62.756027 km
        # of gauge distance is false precision in either.
        "distance_km": round(match.distance_km, 1),
        "elevation_m": round(match.elevation_m, 1),
        "elevation_delta_m": (
            round(match.elevation_delta_m, 1) if match.elevation_delta_m is not None else None
        ),
        "elevation_warning": match.elevation_warning,
        "first_year": match.first_year,
        "last_year": match.last_year,
        "years": match.years,
        "note": match.microclimate_note,
        "provenance": site.get("provenance"),
    }


def _indicative(site: dict) -> dict | None:
    """Suggested terms and the engine's price for them.

    Everything here is already cached --- the fit happened once --- so this is a
    couple of hundred milliseconds of Monte Carlo, not a two-minute wait.
    """
    try:
        terms = service.suggest_contract(site["id"])
    except LookupError:
        return None
    if not terms.get("available"):
        return {"available": False, "reason": terms.get("reason")}

    try:
        priced = service.quote(
            site["id"], terms["peril_id"], terms["year"],
            terms["payout_per_day"], terms["limit"], terms["attachment_days"],
        )
    except (LookupError, ValueError) as exc:
        log.warning("indicative quote failed for %s: %s", site["id"], exc)
        return {"available": False, "reason": str(exc)}

    loads = [
        ("Fair value", priced.get("theo", 0.0),
         "Expected payout under the fitted model. Everything below is what sits on top."),
        ("Capital", priced.get("load_capital", 0.0),
         "Cost of holding capital against the tail of this payout distribution."),
        ("Parameter", priced.get("load_parameter", 0.0),
         "The model's own uncertainty about its estimates, from the block bootstrap."),
        ("Basis", priced.get("load_basis", 0.0),
         "Distance and elevation between your venue and the settlement gauge."),
        ("Expense", priced.get("load_expense", 0.0),
         "Origination, data and settlement — fixed per contract plus a margin on risk carried."),
    ]
    return {
        "available": True,
        "terms": terms,
        "quote": priced,
        "loads": [
            {"label": lbl, "amount": val, "display": catalog.money(int(round(val * 100))),
             "why": why}
            for lbl, val, why in loads
        ],
        "premium_cents": int(round(float(priced.get("mid", 0.0)) * 100)),
    }


@router.post("/configure/{slug}/venue")
async def start_fit(
    request: Request,
    slug: str,
    name: str = Form(...),
    lat: float = Form(...),
    lon: float = Form(...),
    elevation_m: float | None = Form(None),
    vertical: str = Form("Outdoor attraction"),
    season_start_month: int = Form(1),
    season_end_month: int = Form(12),
    notify_email: str | None = Form(None),
) -> JSONResponse:
    """Create the venue, match its station, and start the fit. Returns at once.

    The station match is done synchronously and returned in this response ---
    it is a few milliseconds against an in-memory index, and it is the first
    thing the customer wants to see. Only the century fit goes to the worker.
    """
    product = catalog.get(slug)
    if product is None:
        raise HTTPException(404, "No such service.")
    if not -90 <= lat <= 90 or not -180 <= lon <= 180:
        raise HTTPException(400, "Those coordinates are not on Earth.")
    if vertical not in VERTICALS:
        vertical = "Outdoor attraction"

    account = guest_account(request, email=notify_email or None)
    site = store.create_site(
        account["id"],
        name=name.strip()[:200] or "Unnamed venue",
        lat=lat, lon=lon, elevation_m=elevation_m,
        vertical=vertical,
        season_start_month=max(1, min(12, season_start_month)),
        season_end_month=max(1, min(12, season_end_month)),
        variable_cost_ratio=0.30,
        reserves=None, monthly_burn=None,
        is_example=0,
    )
    # Minted here, where the slug is known, and stored so the link in the
    # notification and the one rendered on screen are the same string.
    token = security.issue_resume_token(site["id"], account["id"], slug)
    store.update_site(
        site["id"],
        resume_token=token,
        contact_email=notify_email.strip()[:200] if notify_email else None,
    )

    match = stations.nearest_station(lat, lon, elevation_m)
    if match is not None:
        store.update_site(site["id"], **service.station_columns(match))

    job = store.create_job(site["id"], "fit")
    submit_fit(site["id"], job["id"])

    fresh = store.get_site(site["id"]) or site
    return JSONResponse(
        {
            "job_id": job["id"],
            "site_id": site["id"],
            # Both carry the token, so the tab that started the fit and any
            # other device work from the same URL.
            "status_url": f"/api/v1/jobs/{job['id']}?t={token}",
            "configure_url": magic_link(fresh, slug, token),
            "resume_link": absolute(request, magic_link(fresh, slug, token)),
            "station": _station_view(fresh),
            "notify": bool(notify_email),
            "mail_configured": SENDER.configured,
        },
        status_code=202,
    )


#: Injected by `main.py` so this module does not import the thread pool.
_submit_fit = None


def submit_fit(site_id: str, job_id: str) -> None:
    """Start a fit, and arrange for the resume link to go out when it lands.

    The `Future` was previously discarded. Keeping it is what makes "you can
    close this tab" true: the notification fires from the worker's completion
    callback rather than from a poller, so nobody has to be watching.

    `add_done_callback` runs even when `fit_site` raised, which is correct ---
    `notify_if_requested` checks the site reached `ready` and declines to send
    otherwise.
    """
    if _submit_fit is None:  # pragma: no cover - wiring error
        raise RuntimeError("fit executor not configured; call web.configure_executor()")

    future = _submit_fit(site_id, job_id)
    if future is not None and hasattr(future, "add_done_callback"):
        future.add_done_callback(lambda _f: notify_if_requested(site_id))


def configure_executor(fn) -> None:
    global _submit_fit
    _submit_fit = fn


@router.get("/api/v1/jobs/{job_id}")
def job_status(request: Request, job_id: str, t: str | None = None) -> JSONResponse:
    """Progress for the configure page's poller.

    Session-scoped rather than bearer-authenticated: the browser polling this
    is the one that started the job. Ownership is still checked --- a job id is
    not a capability.
    """
    job = store.get_job(job_id)
    if job is None:
        raise HTTPException(404, "No such job.")

    site = store.get_site(job["site_id"])
    adopt_resume_token(request, t, job["site_id"])
    account = current_account(request)
    if site and not site.get("is_example"):
        if not account or site["account_id"] != account["id"]:
            raise HTTPException(404, "No such job.")

    payload = {
        "job_id": job["id"],
        "site_id": job["site_id"],
        "status": job["status"],
        "progress": job["progress"],
        "step": job["step"],
        "error": job["error"],
    }
    if job["status"] == "succeeded" and site:
        payload["station"] = _station_view(site)
        payload["site_name"] = site["name"]
        payload["quality"] = json.loads(site["quality"]) if site.get("quality") else None
        if site.get("resume_token"):
            token_payload = security.read_resume_token(site["resume_token"], site_id=site["id"])
            slug = (token_payload or {}).get("slug") or "exposure-report"
            payload["magic_link"] = absolute(request, magic_link(site, slug))
            payload["mail_configured"] = SENDER.configured
            payload["notified"] = bool(site.get("notified_at"))
    return JSONResponse(payload)


@router.get("/api/v1/sites/{site_id}/indicative")
def indicative(request: Request, site_id: str, t: str | None = None) -> JSONResponse:
    site = store.get_site(site_id)
    if site is None:
        raise HTTPException(404, "No such venue.")
    adopt_resume_token(request, t, site_id)
    account = current_account(request)
    if not site.get("is_example") and (not account or site["account_id"] != account["id"]):
        raise HTTPException(404, "No such venue.")
    if site["status"] != "ready":
        raise HTTPException(409, "This venue is still being fitted.")

    result = _indicative(site)
    if result is None:
        raise HTTPException(409, "No model cached for this venue.")
    return JSONResponse(result)


# ----------------------------------------------------------------------
# Magic links
#
# The form on /configure says "leave an address and you can close this tab".
# Making that true needs three things that are easy to get subtly wrong:
#
#   1. the link must authenticate on its own, because the phone that opens it
#      has no cookie from the laptop that started the fit (`api/security.py`);
#   2. it must be sent when the *fit* finishes, not when someone polls --- a
#      poller only exists while the tab is open, which is the case the feature
#      exists to avoid;
#   3. it must point at the service the visitor was actually configuring.
#
# There is no SMTP here, and pretending otherwise would be the same failure this
# rebuild keeps correcting. `ConsoleSender` logs the link and reports itself
# unconfigured, and the configure page then shows the link on screen as
# something to bookmark. Nothing anywhere claims an email was sent.
# ----------------------------------------------------------------------


def magic_link(site: dict, slug: str, token: str | None = None) -> str:
    """The path back to a finished venue.

    Takes the slug explicitly. It used to be hardcoded to `parametric-cover`,
    so a visitor who asked to be emailed about an Exposure Report was sent to a
    different product entirely.
    """
    token = token or site.get("resume_token")
    url = f"/configure/{slug}?site={site['id']}"
    return f"{url}&t={token}" if token else url


def absolute(request: Request, path: str) -> str:
    return str(request.base_url).rstrip("/") + path


class MagicLinkSender(Protocol):
    """Everything the notifier needs from a delivery channel.

    `configured` is part of the contract, not an implementation detail: the UI
    reads it to decide whether to promise an email or offer a link to bookmark.
    """

    configured: bool

    def send(self, to: str, subject: str, link: str) -> None: ...


class ConsoleSender:
    """Logs the link instead of sending it, and says so.

    The default, because this environment has no mail transport. `configured`
    is `False`, which is what stops the UI claiming a message went out.
    """

    configured = False
    name = "console"

    def send(self, to: str, subject: str, link: str) -> None:
        log.info("MAGIC LINK  to=%s  subject=%r  link=%s", to, subject, link)


class SmtpSender:
    """Where a real mail transport plugs in. Not wired, and not pretending to be.

    Same shape as `checkout.StripeProvider`, and refusing for the same reason:
    a channel that silently falls back to logging would let a deployment believe
    it was sending mail when it was not.

    To finish it: read `SMTP_HOST`, `SMTP_PORT`, `SMTP_USER`, `SMTP_PASSWORD`
    and `MAIL_FROM` from the environment --- never from the database --- build a
    `MIMEText` alternative with the link in both parts, and send over
    `smtplib.SMTP` with STARTTLS. Set `configured = True` only once a real host
    is present, since the UI branches on it. Delivery must stay off the fitting
    thread: `notify_if_requested` already runs in a completion callback, so a
    slow relay delays nothing a customer is watching, but a hung socket would
    hold a pool thread --- give the connection an explicit timeout.
    """

    configured = False
    name = "smtp"

    def __init__(self, host: str | None = None) -> None:
        self.host = host

    def send(self, to: str, subject: str, link: str) -> None:
        raise NotImplementedError(
            "SMTP is not configured. See the class docstring for what a real "
            "implementation needs; this deliberately refuses rather than "
            "quietly degrading to a log line."
        )


SENDER: MagicLinkSender = ConsoleSender()


def notify_if_requested(site_id: str) -> bool:
    """Send the resume link once, if one was asked for. Returns whether it sent.

    Called from the fit's completion callback, so every guard here is about not
    sending: the fit may have failed, no address may have been given, and a
    retry must not send twice. `notified_at` is the idempotency record.
    """
    site = store.get_site(site_id)
    if site is None:
        return False
    if site.get("status") != "ready":
        return False  # nothing worth linking to yet
    if not site.get("contact_email") or site.get("notified_at"):
        return False

    token = site.get("resume_token")
    payload = security.read_resume_token(token, site_id=site_id)
    slug = (payload or {}).get("slug") or "exposure-report"
    link = magic_link(site, slug, token)

    try:
        SENDER.send(
            site["contact_email"],
            f"Your {site['name']} analysis is ready",
            link,
        )
    except Exception:  # noqa: BLE001
        # A notifier fault must never turn a good fit into a failed one. Left
        # unmarked so a later attempt can still deliver.
        log.exception("could not send the resume link for %s", site_id)
        return False

    store.update_site(site_id, notified_at=time.time())
    return True


# ----------------------------------------------------------------------
# Cart
# ----------------------------------------------------------------------


@router.post("/cart/add")
async def cart_add(
    request: Request,
    slug: str = Form(...),
    quantity: int = Form(1),
    site_id: str | None = Form(None),
    site_name: str | None = Form(None),
    premium_cents: int | None = Form(None),
    peril_id: str | None = Form(None),
    year: int | None = Form(None),
) -> RedirectResponse:
    product = catalog.get(slug)
    if product is None:
        raise HTTPException(404, "No such service.")

    config: dict[str, Any] = {}
    if product.is_quoted:
        # A quoted line carries the engine's own number. Recomputed server-side
        # rather than trusted from the form, so a edited field cannot set a price.
        if not site_id:
            raise HTTPException(400, "A quoted service needs a venue.")
        site = store.get_site(site_id)
        if site is None or site["status"] != "ready":
            raise HTTPException(409, "That venue is not fitted yet.")
        priced = _indicative(site)
        if not priced or not priced.get("available"):
            raise HTTPException(409, "No indicative price is available for that venue.")
        config = {
            "premium_cents": priced["premium_cents"],
            "peril": priced["terms"]["peril"],
            "peril_id": priced["terms"]["peril_id"],
            "year": priced["terms"]["year"],
            "attachment_days": priced["terms"]["attachment_days"],
            "payout_per_day": priced["terms"]["payout_per_day"],
            "limit": priced["terms"]["limit"],
            "indicative": True,
        }
        site_name = site["name"]

    checkout.add_line(
        request.session, slug, quantity=quantity,
        site_id=site_id or None, site_name=site_name, config=config,
    )
    return RedirectResponse("/cart", status_code=303)


@router.post("/cart/update")
async def cart_update(
    request: Request, index: int = Form(...), quantity: int = Form(...)
) -> RedirectResponse:
    checkout.update_line(request.session, index, quantity)
    return RedirectResponse("/cart", status_code=303)


@router.post("/cart/remove")
async def cart_remove(request: Request, index: int = Form(...)) -> RedirectResponse:
    checkout.remove_line(request.session, index)
    return RedirectResponse("/cart", status_code=303)


@router.get("/cart", response_class=HTMLResponse)
def cart_page(request: Request) -> HTMLResponse:
    return render(request, "cart.html", weather="cloud")


# ----------------------------------------------------------------------
# Checkout
# ----------------------------------------------------------------------


@router.get("/checkout", response_class=HTMLResponse)
def checkout_page(request: Request) -> HTMLResponse:
    cart = checkout.read_cart(request.session)
    if not cart:
        return RedirectResponse("/cart", status_code=303)  # type: ignore[return-value]
    return render(request, "checkout.html", weather="clear")


@router.post("/checkout")
async def place(
    request: Request,
    billing_name: str = Form(...),
    billing_email: str = Form(...),
    billing_company: str = Form(""),
    billing_address: str = Form(""),
) -> RedirectResponse:
    cart = checkout.read_cart(request.session)
    if not cart:
        return RedirectResponse("/cart", status_code=303)

    account = guest_account(request, email=billing_email.strip(), name=billing_name.strip())
    order = checkout.place_order(
        account, cart,
        {
            "name": billing_name.strip()[:200],
            "email": billing_email.strip()[:200],
            "company": billing_company.strip()[:200],
            "address": billing_address.strip()[:500],
        },
    )
    checkout.fulfil(order, submit_fit)
    checkout.clear_cart(request.session)
    request.session["last_order"] = order["id"]
    return RedirectResponse(f"/orders/{order['id']}", status_code=303)


@router.get("/orders/{order_id}", response_class=HTMLResponse)
def order_page(request: Request, order_id: str) -> HTMLResponse:
    account = current_account(request)
    if account is None:
        raise HTTPException(404, "No such order.")
    order = store.get_order(order_id, account_id=account["id"])
    if order is None:
        raise HTTPException(404, "No such order.")
    return render(
        request, "order.html",
        order=checkout.order_view(order),
        just_placed=request.session.pop("last_order", None) == order_id,
        weather="clear",
    )


@router.get("/account", response_class=HTMLResponse)
def account_page(request: Request) -> HTMLResponse:
    account = current_account(request)
    if account is None:
        return render(request, "account.html", orders=[], sites=[], subs=[], weather="cloud")

    sites = [s for s in store.list_sites(account["id"]) if not s.get("is_example")]
    for s in sites:
        s["station"] = _station_view(s)
        s["job"] = store.latest_job(s["id"])
    return render(
        request, "account.html",
        orders=[checkout.order_view(o) for o in store.list_orders(account["id"])],
        sites=sites,
        subs=store.list_subscriptions(account["id"]),
        weather="cloud",
    )


@router.post("/account/subscriptions/{sub_id}/cancel")
async def cancel_sub(request: Request, sub_id: str) -> RedirectResponse:
    account = current_account(request)
    if account:
        store.cancel_subscription(sub_id, account["id"])
    return RedirectResponse("/account", status_code=303)
